apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db-designer.fullname" . }}-ui
  labels:
    {{- include "db-designer.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      {{- include "db-designer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      annotations:
        checksum/ui-env: {{ include (print $.Template.BasePath "/configmap-ui-env.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "db-designer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      serviceAccountName: {{ include "db-designer.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          image: {{ include "db-designer.image.ui" . | quote }}
          imagePullPolicy: {{ .Values.image.ui.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: HOME
              value: /tmp
          ports:
            - name: http
              containerPort: {{ .Values.service.ui.port }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          volumeMounts:
            - name: ui-env
              mountPath: /app/build/environment-config.js
              subPath: environment-config.js
              readOnly: true
      volumes:
        - name: ui-env
          configMap:
            name: {{ include "db-designer.fullname" . }}-ui-env
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
