apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-designer.fullname" . }}-ui
  labels:
    {{- include "db-designer.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ui.port }}
      targetPort: http
  selector:
    {{- include "db-designer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
