#!/bin/bash
# Start the sink connector (Solace -> Database).
# Run from inside the "DB Connector" directory.
#
# Before running, this directory must contain (supplied per deployment
# from the DB Designer connector package, see ../README.md):
#   - dependencies/entity.jar          generated by the DB CLI
#   - configs/sink/application-db-processor.yml (imported by the
#     operator config below via spring.config.import)
#
# Use a management port distinct from the source connector (9002) so
# both directions can run on the same host at the same time.
java -cp ./pubsubplus-connector-database-2.0.2.jar \
  -D"loader.path=./dependencies,./configs/sink" \
  org.springframework.boot.loader.launch.PropertiesLauncher \
  --spring.config.additional-location="./configs/sink/application-operator.yml" \
  --management.server.port=9003
