#!/bin/bash
# Start the source connector (Database -> Solace).
# Run from inside the "DB Connector" directory.
#
# Before running, this directory must contain (supplied per deployment
# from the DB Designer connector package, see ../README.md):
#   - dependencies/entity.jar          generated by the DB CLI
#   - configs/source/application-db-processor.yml (imported by the
#     operator config below via spring.config.import)
java -cp ./pubsubplus-connector-database-2.0.2.jar \
  -D"loader.path=./dependencies,./configs/source" \
  org.springframework.boot.loader.launch.PropertiesLauncher \
  --spring.config.additional-location="./configs/source/application-operator.yml" \
  --management.server.port=9002
