#!/bin/bash
set -euo pipefail

# =============================================================
# generate-manifest.sh -- regenerate the static tool manifest in
# connectors/SAM K8s Mesh.yaml from the LIVE K8s platform API.
# =============================================================
# Why: the MCP entrypoint names its tools <card>_<skill id>, and
# the card name of a DB-managed agent is its instanceName
# (agent_<uuid with underscores>) -- NOT the display name. The
# UUIDs change whenever the platform DB is rebuilt (stop.sh),
# so the manifest must be regenerated after every teardown.
#
# Requires a valid sam CLI login against the K8s platform
# (sam auth login solace-lab --url https://sam.solace.lab).
#
# Default: the four retail demo agents. --all includes every
# deployed standard agent (Builder, web agents, ...).
# =============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=../lib/common.sh
. "$SCRIPT_DIR/../lib/common.sh"

K8S_URL="${SAM_K8S_URL:-https://sam.solace.lab}"
CONNECTOR_FILE="$SCRIPT_DIR/connectors/SAM K8s Mesh.yaml"
INCLUDE_ALL="${1:-}"

load_env "$PROJECT_DIR"
sam_auth_token

AGENTS_JSON=$(curl -sk -H "Authorization: Bearer $SAM_AUTH_TOKEN" \
  "$K8S_URL/api/v1/platform/agents")

MANIFEST_BLOCK=$(AGENTS_JSON="$AGENTS_JSON" python3 - "$INCLUDE_ALL" <<'PYEOF'
import json, os, re, sys, textwrap

include_all = sys.argv[1] == "--all"
retail = {
    "Retail CRM Query Expert",
    "Retail OMS Query Expert",
    "Retail PDM Query Expert",
    "Retail 360 Reporter",
}

d = json.loads(os.environ["AGENTS_JSON"])
agents = d if isinstance(d, list) else d.get("data", d.get("agents", []))

def sanitize(s):
    return re.sub(r"[^a-z0-9_]", "_", s.lower())

lines = []
count = 0
for a in agents:
    if a.get("deploymentStatus") != "deployed":
        continue
    if not include_all and a.get("name") not in retail:
        continue
    card = a.get("instanceName") or a.get("name")
    for s in a.get("skills") or []:
        tool = f"{sanitize(card)}_{sanitize(s['id'])}"
        desc = (f"{s.get('description') or s.get('name') or s['id']} "
                f"(K8s mesh agent: {a.get('name')})")
        desc = " ".join(desc.split())
        lines.append(f"      - name: {tool}")
        lines.append("        description: >-")
        for chunk in textwrap.wrap(desc, 60):
            lines.append(f"          {chunk}")
        lines.append("        inputSchema:")
        lines.append("          type: object")
        lines.append("          properties:")
        lines.append("            message:")
        lines.append("              type: string")
        lines.append("              description: The message or request to send to the agent")
        lines.append("          required:")
        lines.append("            - message")
        count += 1

if count == 0:
    sys.exit("no deployed agents matched; manifest would be empty")
print("\n".join(lines))
print(f"generated {count} tool entries", file=sys.stderr)
PYEOF
)

cat > "$CONNECTOR_FILE" <<EOF
# GENERATED by generate-manifest.sh -- edit the generator, not
# this file. Regenerate after every K8s platform rebuild: tool
# names embed the DB UUIDs (agent instanceName), which change
# when stop.sh destroys the platform DB.
#
# MCP connector to the local Kubernetes SAM deployment. Uses the
# same MCP entrypoint as Claude Code (Streamable HTTP + OAuth 2.1
# discovery against the cluster Keycloak).
#
# The static tool manifest below is REQUIRED: the entrypoint
# blocks tools/list until the user completes OAuth, and without
# a manifest the desktop runtime refuses the MCP client at agent
# startup ("failed to add MCP client ... requires a manifest").
# It must be a real YAML list (a JSON string is rejected). Every
# entrypoint tool takes one required string field "message".
kind: connector
name: SAM K8s Mesh
description: >-
  Local Kubernetes Solace Agent Mesh (sam.solace.lab) exposed via
  its MCP entrypoint. Provides the retail demo agents (CRM, OMS
  and PDM query experts, Retail 360 Reporter) as callable tools.
spec:
  type: mcp
  subtype: remote
  values:
    server_url: https://sam.solace.lab/gw/dev
    connection_type: streamable-http
    auth_type: oauth
    auth_oauth_mode: discovery
    manifest:
$MANIFEST_BLOCK
EOF

echo "Wrote $CONNECTOR_FILE"
echo "Apply it with ./connect.sh"
