##spring.datasource.url= jdbc:postgresql://localhost:5432/ccc_connectors?useSSL=false
##spring.datasource.username= postgres
##spring.datasource.password= postgres
##
##spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
##
### Hibernate ddl auto (create, create-drop, validate, update)
##spring.jpa.hibernate.ddl-auto= update
##db.schema.name=control_center_schema
#
server.port=8082

###Oracle localhost#######

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
spring.datasource.username=CM_SCHEMA
spring.datasource.password=CM_SCHEMA
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.hibernate.ddl-auto=update
db.schema.name=CM_SCHEMA
