
########## oracle ############
get.db.schema.tables=SELECT table_name FROM (SELECT table_name AS table_name FROM all_tables WHERE owner = '%s' UNION SELECT view_name AS table_name FROM all_views WHERE owner = '%s') ORDER BY table_name
get.db.schema.table.columns=SELECT column_name ,data_type FROM all_tab_columns WHERE owner='%s' and table_name='%s'
get.db.schema.table.foreignKeys= SELECT a.table_name, a.column_name, a.constraint_name, c.owner, c.r_owner "foreign_table_schema", c_pk.table_name "foreign_table_name", c_pk.constraint_name r_pk FROM all_cons_columns a JOIN all_constraints c ON a.owner = c.owner AND a.constraint_name = c.constraint_name JOIN all_constraints c_pk ON c.r_owner = c_pk.owner AND c.r_constraint_name = c_pk.constraint_name WHERE c.constraint_type = 'R' AND c.owner='%s' AND a.table_name='%s'

