######### sap ###########
get.db.schema.tables=SELECT TABLE_NAME AS "TABLE_NAME" FROM SYS.TABLES WHERE SCHEMA_NAME = '%s'
get.db.schema.table.columns=SELECT COLUMN_NAME AS "COLUMN_NAME", DATA_TYPE_NAME AS "DATA_TYPE" FROM SYS.COLUMNS WHERE SCHEMA_NAME = '%s' AND TABLE_NAME = '%s'
get.db.schema.table.foreignKeys=SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME AS "foreign_table_name", REFERENCED_COLUMN_NAME AS "foreign_column_name" FROM SYS."REFERENTIAL_CONSTRAINTS" WHERE SCHEMA_NAME = '%s' AND TABLE_NAME = '%s'

