#!/usr/bin/env bash
# End-to-end smoke test for the Topic Compaction MI running in docker-compose.
#
# Prerequisites:
#   - docker compose up has been run from deploy/docker-compose/
#   - solace-broker is healthy on http://localhost:8080 (admin/admin)
#   - topic-compaction-mi is up on http://localhost:8090
#
# Usage:
#   ./examples/smoke-test.sh
set -euo pipefail

BROKER_REST="${BROKER_REST:-http://localhost:19000}"
MI_REST="${MI_REST:-http://localhost:18090}"
BROKER_SEMP="${BROKER_SEMP:-http://localhost:18080}"
SOLACE_USER="${SOLACE_USER:-default}"
SOLACE_PASS="${SOLACE_PASS:-default}"

step() { echo; echo "===== $* ====="; }

step "1. Publish three messages on different topics"
curl -fsS -u "${SOLACE_USER}:${SOLACE_PASS}" \
  -X POST "${BROKER_REST}/TOPIC/orders/created/A" \
  -H 'Content-Type: application/json' \
  -d '{"orderId":"A","amount":10}'
curl -fsS -u "${SOLACE_USER}:${SOLACE_PASS}" \
  -X POST "${BROKER_REST}/TOPIC/orders/created/B" \
  -H 'Content-Type: application/json' \
  -d '{"orderId":"B","amount":20}'
curl -fsS -u "${SOLACE_USER}:${SOLACE_PASS}" \
  -X POST "${BROKER_REST}/TOPIC/orders/created/C" \
  -H 'Content-Type: application/json' \
  -d '{"orderId":"C","amount":30}'
echo "Published 3 messages."
sleep 2

step "2. Verify the KV store contains all three keys via REST"
curl -fsS "${MI_REST}/api/v1/kv?prefix=orders/" | jq

step "3. Read latest message for orders/created/B"
curl -fsS "${MI_REST}/api/v1/kv/orders%2Fcreated%2FB"

step "4. Update orders/created/A and verify the latest is reflected"
curl -fsS -u "${SOLACE_USER}:${SOLACE_PASS}" \
  -X POST "${BROKER_REST}/TOPIC/orders/created/A" \
  -H 'Content-Type: application/json' \
  -d '{"orderId":"A","amount":99,"updated":true}'
sleep 2
curl -fsS "${MI_REST}/api/v1/kv/orders%2Fcreated%2FA"

step "5. Trigger replay via command event - watch for the /compacted topic"
echo "Subscribe in another terminal: curl -fsSN -u default:default '${BROKER_REST}/SUBSCRIBE/orders/created/A/compacted'"
echo
read -p "Press ENTER once you're subscribed..."

curl -fsS -u "${SOLACE_USER}:${SOLACE_PASS}" \
  -X POST "${BROKER_REST}/TOPIC/compacted/command/replay" \
  -H 'Content-Type: application/json' \
  -d "$(cat $(dirname "$0")/command-events/replay-minimal.json | sed 's|orders/created/12345|orders/created/A|')"
echo "Sent replay command; the subscriber should now see orders/created/A on orders/created/A/compacted"
sleep 2

step "6. Test Solace Request/Reply Lookup"
echo "Use the SDK CLI or any Solace client:"
echo "  Request topic: compacted/lookup/orders/created/A"
echo "  Reply-to:      <auto-generated>"
echo "  Header:        x-compaction-key: orders/created/A (optional, topic tail also works)"

step "7. Tombstone via REST"
curl -fsS -X DELETE "${MI_REST}/api/v1/kv/orders%2Fcreated%2FC"
curl -fsS -o /dev/null -w "DELETE result: HTTP %{http_code}\n" \
  "${MI_REST}/api/v1/kv/orders%2Fcreated%2FC"

step "8. Inspect Prometheus metrics"
curl -fsS "${MI_REST}/actuator/prometheus" | grep -E '^topic_compaction_'

echo
echo "Smoke test complete. Topic Compaction MI is functioning end-to-end."
