package com.solace.connectors.database.sink.entity;
// Generated Aug 22, 2025, 9:12:25 AM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * LogisticsEventheader generated by hbm2java
 */
@Entity
@Table(name="LOGISTICS_EVENTHEADER"
    ,schema="TESTSCHEMA"
)
public class LogisticsEventheader implements java.io.Serializable {


     private String traceid;
     private String holderid;
     private String holdertype;
     private String source;
     private String storeid;
     private String exportdate;
     private String holdersecuritysealbarcode;
     private String holderregistrationnumber;
     private String containerbarcode;
     private String containersealbarcode;
     private String type;
     private String operationtype;

    public LogisticsEventheader() {
    }

	
    public LogisticsEventheader(String traceid) {
        this.traceid = traceid;
    }
    public LogisticsEventheader(String traceid, String holderid, String holdertype, String source, String storeid, String exportdate, String holdersecuritysealbarcode, String holderregistrationnumber, String containerbarcode, String containersealbarcode, String type, String operationtype) {
       this.traceid = traceid;
       this.holderid = holderid;
       this.holdertype = holdertype;
       this.source = source;
       this.storeid = storeid;
       this.exportdate = exportdate;
       this.holdersecuritysealbarcode = holdersecuritysealbarcode;
       this.holderregistrationnumber = holderregistrationnumber;
       this.containerbarcode = containerbarcode;
       this.containersealbarcode = containersealbarcode;
       this.type = type;
       this.operationtype = operationtype;
    }
   
     @Id 

    
    @Column(name="TRACEID", nullable=false)
    public String getTraceid() {
        return this.traceid;
    }
    
    public void setTraceid(String traceid) {
        this.traceid = traceid;
    }

    
    @Column(name="HOLDERID")
    public String getHolderid() {
        return this.holderid;
    }
    
    public void setHolderid(String holderid) {
        this.holderid = holderid;
    }

    
    @Column(name="HOLDERTYPE")
    public String getHoldertype() {
        return this.holdertype;
    }
    
    public void setHoldertype(String holdertype) {
        this.holdertype = holdertype;
    }

    
    @Column(name="SOURCE")
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="STOREID")
    public String getStoreid() {
        return this.storeid;
    }
    
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    
    @Column(name="EXPORTDATE")
    public String getExportdate() {
        return this.exportdate;
    }
    
    public void setExportdate(String exportdate) {
        this.exportdate = exportdate;
    }

    
    @Column(name="HOLDERSECURITYSEALBARCODE")
    public String getHoldersecuritysealbarcode() {
        return this.holdersecuritysealbarcode;
    }
    
    public void setHoldersecuritysealbarcode(String holdersecuritysealbarcode) {
        this.holdersecuritysealbarcode = holdersecuritysealbarcode;
    }

    
    @Column(name="HOLDERREGISTRATIONNUMBER")
    public String getHolderregistrationnumber() {
        return this.holderregistrationnumber;
    }
    
    public void setHolderregistrationnumber(String holderregistrationnumber) {
        this.holderregistrationnumber = holderregistrationnumber;
    }

    
    @Column(name="CONTAINERBARCODE")
    public String getContainerbarcode() {
        return this.containerbarcode;
    }
    
    public void setContainerbarcode(String containerbarcode) {
        this.containerbarcode = containerbarcode;
    }

    
    @Column(name="CONTAINERSEALBARCODE")
    public String getContainersealbarcode() {
        return this.containersealbarcode;
    }
    
    public void setContainersealbarcode(String containersealbarcode) {
        this.containersealbarcode = containersealbarcode;
    }

    
    @Column(name="TYPE")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="OPERATIONTYPE")
    public String getOperationtype() {
        return this.operationtype;
    }
    
    public void setOperationtype(String operationtype) {
        this.operationtype = operationtype;
    }




}


