package com.solace.connectors.database.sink.entity;
// Generated May 6, 2025, 5:10:01 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name="MESSAGES"
    ,schema="dbo"
    ,catalog="MASTERULIS"
)
public class Messages implements java.io.Serializable {


     private Integer idMessage;
     private String topic;
     private String message;
     private Date createdate;
     private String status;
     private Integer retrycount;
     private Date lastupdated;

    public Messages() {
    }

	
    public Messages(Integer idMessage) {
        this.idMessage = idMessage;
    }
    public Messages(Integer idMessage, String topic, String message, Date createdate, String status, Integer retrycount, Date lastupdated) {
       this.idMessage = idMessage;
       this.topic = topic;
       this.message = message;
       this.createdate = createdate;
       this.status = status;
       this.retrycount = retrycount;
       this.lastupdated = lastupdated;
    }
   
     @Id 

    
    @Column(name="ID_MESSAGE", unique=true, nullable=false)
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }

    
    @Column(name="TOPIC")
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }

    
    @Column(name="MESSAGE")
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="CREATEDATE", length=27)
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    
    @Column(name="STATUS", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="RETRYCOUNT")
    public Integer getRetrycount() {
        return this.retrycount;
    }
    
    public void setRetrycount(Integer retrycount) {
        this.retrycount = retrycount;
    }

    
    @Column(name="LASTUPDATED", length=27)
    public Date getLastupdated() {
        return this.lastupdated;
    }
    
    public void setLastupdated(Date lastupdated) {
        this.lastupdated = lastupdated;
    }




}


