package com.solace.connectors.database.sink.entity;
// Generated Nov 3, 2025, 4:50:32 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * OggFeedback generated by hbm2java
 */
@Entity
@Table(name="OGG_FEEDBACK"
    ,schema="C##TEST"
)
public class OggFeedback  implements java.io.Serializable {


     private String feedbackId;
     private String playerId;
     private String campaignName;
     private String rating;
     private String sentimentScore;
     private String feedbackDate;

    public OggFeedback() {
    }

	
    public OggFeedback(String feedbackId) {
        this.feedbackId = feedbackId;
    }
    public OggFeedback(String feedbackId, String playerId, String campaignName, String rating, String sentimentScore, String feedbackDate) {
       this.feedbackId = feedbackId;
       this.playerId = playerId;
       this.campaignName = campaignName;
       this.rating = rating;
       this.sentimentScore = sentimentScore;
       this.feedbackDate = feedbackDate;
    }
   
     @Id 

    
    @Column(name="FEEDBACK_ID", unique=true, nullable=false)
    public String getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(String feedbackId) {
        this.feedbackId = feedbackId;
    }

    
    @Column(name="PLAYER_ID")
    public String getPlayerId() {
        return this.playerId;
    }
    
    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    
    @Column(name="CAMPAIGN_NAME")
    public String getCampaignName() {
        return this.campaignName;
    }
    
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    
    @Column(name="RATING")
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }

    
    @Column(name="SENTIMENT_SCORE")
    public String getSentimentScore() {
        return this.sentimentScore;
    }
    
    public void setSentimentScore(String sentimentScore) {
        this.sentimentScore = sentimentScore;
    }

    
    @Column(name="FEEDBACK_DATE")
    public String getFeedbackDate() {
        return this.feedbackDate;
    }
    
    public void setFeedbackDate(String feedbackDate) {
        this.feedbackDate = feedbackDate;
    }




}


