package com.solace.connectors.database.sink.entity;
// Generated Nov 3, 2025, 4:50:32 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * OggNotification generated by hbm2java
 */
@Entity
@Table(name="OGG_NOTIFICATION"
    ,schema="C##TEST"
)
public class OggNotification  implements java.io.Serializable {


     private String eventId;
     private String playerId;
     private String notificationType;
     private String channel;
     private String sentTime;
     private String openTime;
     private String clickedFlag;

    public OggNotification() {
    }

	
    public OggNotification(String eventId) {
        this.eventId = eventId;
    }
    public OggNotification(String eventId, String playerId, String notificationType, String channel, String sentTime, String openTime, String clickedFlag) {
       this.eventId = eventId;
       this.playerId = playerId;
       this.notificationType = notificationType;
       this.channel = channel;
       this.sentTime = sentTime;
       this.openTime = openTime;
       this.clickedFlag = clickedFlag;
    }
   
     @Id 

    
    @Column(name="EVENT_ID", unique=true, nullable=false)
    public String getEventId() {
        return this.eventId;
    }
    
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    
    @Column(name="PLAYER_ID")
    public String getPlayerId() {
        return this.playerId;
    }
    
    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    
    @Column(name="NOTIFICATION_TYPE")
    public String getNotificationType() {
        return this.notificationType;
    }
    
    public void setNotificationType(String notificationType) {
        this.notificationType = notificationType;
    }

    
    @Column(name="CHANNEL")
    public String getChannel() {
        return this.channel;
    }
    
    public void setChannel(String channel) {
        this.channel = channel;
    }

    
    @Column(name="SENT_TIME")
    public String getSentTime() {
        return this.sentTime;
    }
    
    public void setSentTime(String sentTime) {
        this.sentTime = sentTime;
    }

    
    @Column(name="OPEN_TIME")
    public String getOpenTime() {
        return this.openTime;
    }
    
    public void setOpenTime(String openTime) {
        this.openTime = openTime;
    }

    
    @Column(name="CLICKED_FLAG")
    public String getClickedFlag() {
        return this.clickedFlag;
    }
    
    public void setClickedFlag(String clickedFlag) {
        this.clickedFlag = clickedFlag;
    }




}


