package com.solace.connectors.database.sink.entity;
// Generated Nov 3, 2025, 4:50:32 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * OggPurchase generated by hbm2java
 */
@Entity
@Table(name="OGG_PURCHASE"
    ,schema="C##TEST"
)
public class OggPurchase  implements java.io.Serializable {


     private String purchaseId;
     private String playerId;
     private String itemName;
     private String itemCategory;
     private String purchaseAmount;
     private String currencyCode;
     private String purchaseTime;
     private String paymentMethod;

    public OggPurchase() {
    }

	
    public OggPurchase(String purchaseId) {
        this.purchaseId = purchaseId;
    }
    public OggPurchase(String purchaseId, String playerId, String itemName, String itemCategory, String purchaseAmount, String currencyCode, String purchaseTime, String paymentMethod) {
       this.purchaseId = purchaseId;
       this.playerId = playerId;
       this.itemName = itemName;
       this.itemCategory = itemCategory;
       this.purchaseAmount = purchaseAmount;
       this.currencyCode = currencyCode;
       this.purchaseTime = purchaseTime;
       this.paymentMethod = paymentMethod;
    }
   
     @Id 

    
    @Column(name="PURCHASE_ID", unique=true, nullable=false)
    public String getPurchaseId() {
        return this.purchaseId;
    }
    
    public void setPurchaseId(String purchaseId) {
        this.purchaseId = purchaseId;
    }

    
    @Column(name="PLAYER_ID")
    public String getPlayerId() {
        return this.playerId;
    }
    
    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    
    @Column(name="ITEM_NAME")
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    
    @Column(name="ITEM_CATEGORY")
    public String getItemCategory() {
        return this.itemCategory;
    }
    
    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }

    
    @Column(name="PURCHASE_AMOUNT")
    public String getPurchaseAmount() {
        return this.purchaseAmount;
    }
    
    public void setPurchaseAmount(String purchaseAmount) {
        this.purchaseAmount = purchaseAmount;
    }

    
    @Column(name="CURRENCY_CODE")
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="PURCHASE_TIME")
    public String getPurchaseTime() {
        return this.purchaseTime;
    }
    
    public void setPurchaseTime(String purchaseTime) {
        this.purchaseTime = purchaseTime;
    }

    
    @Column(name="PAYMENT_METHOD")
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }




}


