package com.solace.connectors.database.sink.entity;
// Generated Nov 3, 2025, 5:45:23 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * OggSession generated by hbm2java
 */
@Entity
@Table(name="OGG_SESSION"
    ,schema="C##TEST"
)
public class OggSession implements java.io.Serializable {


     private String sessionId;
     private String score;
     private String sessionStartTime;
     private String sessionEndTime;
     private String sessionDuration;
     private String deviceType;
     private String region;
     private String exitReason;
     private String playerId;

    public OggSession() {
    }

	
    public OggSession(String sessionId) {
        this.sessionId = sessionId;
    }
    public OggSession(String sessionId, String score, String sessionStartTime, String sessionEndTime, String sessionDuration, String deviceType, String region, String exitReason, String playerId) {
       this.sessionId = sessionId;
       this.score = score;
       this.sessionStartTime = sessionStartTime;
       this.sessionEndTime = sessionEndTime;
       this.sessionDuration = sessionDuration;
       this.deviceType = deviceType;
       this.region = region;
       this.exitReason = exitReason;
       this.playerId = playerId;
    }
   
     @Id 

    
    @Column(name="SESSION_ID", unique=true, nullable=false)
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    
    @Column(name="SCORE")
    public String getScore() {
        return this.score;
    }
    
    public void setScore(String score) {
        this.score = score;
    }

    
    @Column(name="SESSION_START_TIME")
    public String getSessionStartTime() {
        return this.sessionStartTime;
    }
    
    public void setSessionStartTime(String sessionStartTime) {
        this.sessionStartTime = sessionStartTime;
    }

    
    @Column(name="SESSION_END_TIME")
    public String getSessionEndTime() {
        return this.sessionEndTime;
    }
    
    public void setSessionEndTime(String sessionEndTime) {
        this.sessionEndTime = sessionEndTime;
    }

    
    @Column(name="SESSION_DURATION")
    public String getSessionDuration() {
        return this.sessionDuration;
    }
    
    public void setSessionDuration(String sessionDuration) {
        this.sessionDuration = sessionDuration;
    }

    
    @Column(name="DEVICE_TYPE")
    public String getDeviceType() {
        return this.deviceType;
    }
    
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    
    @Column(name="REGION")
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    
    @Column(name="EXIT_REASON")
    public String getExitReason() {
        return this.exitReason;
    }
    
    public void setExitReason(String exitReason) {
        this.exitReason = exitReason;
    }

    
    @Column(name="PLAYER_ID")
    public String getPlayerId() {
        return this.playerId;
    }
    
    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }




}


