package com.solace.connectors.database.sink.entity;
// Generated Nov 11, 2025, 8:21:54 AM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="ORDERS"
    ,schema="PUBLIC"
    ,catalog="PUBLIC"
)
public class Orders implements java.io.Serializable {


     private BigDecimal orderId;
     private BigDecimal customerNumber;
     private String orderAmount;
     private String orderInfo;
     private String orderName;

    public Orders() {
    }

	
    public Orders(BigDecimal orderId) {
        this.orderId = orderId;
    }
    public Orders(BigDecimal orderId, BigDecimal customerNumber, String orderAmount, String orderInfo, String orderName) {
       this.orderId = orderId;
       this.customerNumber = customerNumber;
       this.orderAmount = orderAmount;
       this.orderInfo = orderInfo;
       this.orderName = orderName;
    }
   
     @Id 

    
    @Column(name="ORDER_ID", unique=true, nullable=false)
    public BigDecimal getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(BigDecimal orderId) {
        this.orderId = orderId;
    }

    
    @Column(name="CUSTOMER_NUMBER")
    public BigDecimal getCustomerNumber() {
        return this.customerNumber;
    }
    
    public void setCustomerNumber(BigDecimal customerNumber) {
        this.customerNumber = customerNumber;
    }

    
    @Column(name="ORDER_AMOUNT")
    public String getOrderAmount() {
        return this.orderAmount;
    }
    
    public void setOrderAmount(String orderAmount) {
        this.orderAmount = orderAmount;
    }

    
    @Column(name="ORDER_INFO")
    public String getOrderInfo() {
        return this.orderInfo;
    }
    
    public void setOrderInfo(String orderInfo) {
        this.orderInfo = orderInfo;
    }

    
    @Column(name="ORDER_NAME")
    public String getOrderName() {
        return this.orderName;
    }
    
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }




}


