package com.solace.connectors.database.sink.entity;
// Generated Nov 4, 2025, 5:47:46 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * PgbenchBranches generated by hbm2java
 */
@Entity
@Table(name="PGBENCH_BRANCHES"
    ,schema="C##TEST"
)
public class PgbenchBranches implements java.io.Serializable {


     private BigDecimal bid;
     private BigDecimal bbalance;
     private String filler;
     private BigDecimal test2;

    public PgbenchBranches() {
    }

	
    public PgbenchBranches(BigDecimal bid) {
        this.bid = bid;
    }
    public PgbenchBranches(BigDecimal bid, BigDecimal bbalance, String filler, BigDecimal test2) {
       this.bid = bid;
       this.bbalance = bbalance;
       this.filler = filler;
       this.test2 = test2;
    }
   
     @Id 

    
    @Column(name="BID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getBid() {
        return this.bid;
    }
    
    public void setBid(BigDecimal bid) {
        this.bid = bid;
    }

    
    @Column(name="BBALANCE", precision=22, scale=0)
    public BigDecimal getBbalance() {
        return this.bbalance;
    }
    
    public void setBbalance(BigDecimal bbalance) {
        this.bbalance = bbalance;
    }

    
    @Column(name="FILLER")
    public String getFiller() {
        return this.filler;
    }
    
    public void setFiller(String filler) {
        this.filler = filler;
    }

    
    @Column(name="TEST2", precision=22, scale=0)
    public BigDecimal getTest2() {
        return this.test2;
    }
    
    public void setTest2(BigDecimal test2) {
        this.test2 = test2;
    }




}


