package com.solace.connectors.database.sink.entity;
// Generated Jul 23, 2025, 2:01:09 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * PgbenchTellers generated by hbm2java
 */
@Entity
@Table(name="PGBENCH_TELLERS"
    ,schema="C##TEST"
)
public class PgbenchTellers  implements java.io.Serializable {


     private BigDecimal tid;
     private BigDecimal bid;
     private BigDecimal tbalance;
     private String filler;

    public PgbenchTellers() {
    }

	
    public PgbenchTellers(BigDecimal tid) {
        this.tid = tid;
    }
    public PgbenchTellers(BigDecimal tid, BigDecimal bid, BigDecimal tbalance, String filler) {
       this.tid = tid;
       this.bid = bid;
       this.tbalance = tbalance;
       this.filler = filler;
    }
   
     @Id 

    
    @Column(name="TID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getTid() {
        return this.tid;
    }
    
    public void setTid(BigDecimal tid) {
        this.tid = tid;
    }

    
    @Column(name="BID", precision=22, scale=0)
    public BigDecimal getBid() {
        return this.bid;
    }
    
    public void setBid(BigDecimal bid) {
        this.bid = bid;
    }

    
    @Column(name="TBALANCE", precision=22, scale=0)
    public BigDecimal getTbalance() {
        return this.tbalance;
    }
    
    public void setTbalance(BigDecimal tbalance) {
        this.tbalance = tbalance;
    }

    
    @Column(name="FILLER")
    public String getFiller() {
        return this.filler;
    }
    
    public void setFiller(String filler) {
        this.filler = filler;
    }




}


