package com.solace.connectors.database.sink.entity;
// Generated Jul 23, 2025, 2:01:09 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * PgbenchAccounts generated by hbm2java
 */
@Entity
@Table(name="PGBENCH_ACCOUNTS"
    ,schema="C##TEST"
)
public class PgbenchAccounts  implements java.io.Serializable {


     private BigDecimal aid;
     private BigDecimal bid;
     private BigDecimal abalance;
     private String filler;

    public PgbenchAccounts() {
    }

	
    public PgbenchAccounts(BigDecimal aid) {
        this.aid = aid;
    }
    public PgbenchAccounts(BigDecimal aid, BigDecimal bid, BigDecimal abalance, String filler) {
       this.aid = aid;
       this.bid = bid;
       this.abalance = abalance;
       this.filler = filler;
    }
   
     @Id 

    
    @Column(name="AID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getAid() {
        return this.aid;
    }
    
    public void setAid(BigDecimal aid) {
        this.aid = aid;
    }

    
    @Column(name="BID", precision=22, scale=0)
    public BigDecimal getBid() {
        return this.bid;
    }
    
    public void setBid(BigDecimal bid) {
        this.bid = bid;
    }

    
    @Column(name="ABALANCE", precision=22, scale=0)
    public BigDecimal getAbalance() {
        return this.abalance;
    }
    
    public void setAbalance(BigDecimal abalance) {
        this.abalance = abalance;
    }

    
    @Column(name="FILLER")
    public String getFiller() {
        return this.filler;
    }
    
    public void setFiller(String filler) {
        this.filler = filler;
    }




}


