package com.solace.connectors.database.sink.entity;
// Generated Jul 23, 2025, 2:01:09 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * PgbenchHistory generated by hbm2java
 */
@Entity
@Table(name="PGBENCH_HISTORY"
    ,schema="C##TEST"
)
public class PgbenchHistory  implements java.io.Serializable {


     private BigDecimal tid;
     private BigDecimal bid;
     private BigDecimal aid;
     private BigDecimal delta;
     private String mtime;
     private String filler;

    public PgbenchHistory() {
    }

	
    public PgbenchHistory(BigDecimal tid) {
        this.tid = tid;
    }
    public PgbenchHistory(BigDecimal tid, BigDecimal bid, BigDecimal aid, BigDecimal delta, String mtime, String filler) {
       this.tid = tid;
       this.bid = bid;
       this.aid = aid;
       this.delta = delta;
       this.mtime = mtime;
       this.filler = filler;
    }
   
     @Id 

    
    @Column(name="TID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getTid() {
        return this.tid;
    }
    
    public void setTid(BigDecimal tid) {
        this.tid = tid;
    }

    
    @Column(name="BID", precision=22, scale=0)
    public BigDecimal getBid() {
        return this.bid;
    }
    
    public void setBid(BigDecimal bid) {
        this.bid = bid;
    }

    
    @Column(name="AID", precision=22, scale=0)
    public BigDecimal getAid() {
        return this.aid;
    }
    
    public void setAid(BigDecimal aid) {
        this.aid = aid;
    }

    
    @Column(name="DELTA", precision=22, scale=0)
    public BigDecimal getDelta() {
        return this.delta;
    }
    
    public void setDelta(BigDecimal delta) {
        this.delta = delta;
    }

    
    @Column(name="MTIME")
    public String getMtime() {
        return this.mtime;
    }
    
    public void setMtime(String mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="FILLER")
    public String getFiller() {
        return this.filler;
    }
    
    public void setFiller(String filler) {
        this.filler = filler;
    }




}


