package com.solace.connectors.database.sink.entity;
// Generated Jul 11, 2025, 7:40:54 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * SinkOrdersEdb generated by hbm2java
 */
@Entity
@Table(name="sink_orders_edb"
    ,schema="public"
)
public class SinkOrdersEdb implements java.io.Serializable {


     private String orderId;
     private String custId;
     private String orderDate;
     private String status;
     private String customer;

    public SinkOrdersEdb() {
    }

	
    public SinkOrdersEdb(String orderId) {
        this.orderId = orderId;
    }
    public SinkOrdersEdb(String orderId, String custId, String orderDate, String status, String customer) {
       this.orderId = orderId;
       this.custId = custId;
       this.orderDate = orderDate;
       this.status = status;
       this.customer = customer;
    }
   
     @Id 

    
    @Column(name="order_id", unique=true, nullable=false)
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    
    @Column(name="cust_id")
    public String getCustId() {
        return this.custId;
    }
    
    public void setCustId(String custId) {
        this.custId = custId;
    }

    
    @Column(name="order_date")
    public String getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="customer")
    public String getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(String customer) {
        this.customer = customer;
    }




}


