package com.solace.connectors.database.sink.entity;
// Generated Jul 11, 2025, 7:19:17 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * SinkOrders generated by hbm2java
 */
@Entity
@Table(name="SINK_ORDERS"
        ,schema="C##TEST"
)
public class SinkOrders  implements java.io.Serializable {


    private String orderId;
    private String custId;
    private String orderDate;
    private String status;
    private String customer;

    public SinkOrders() {
    }


    public SinkOrders(String orderId) {
        this.orderId = orderId;
    }
    public SinkOrders(String orderId, String custId, String orderDate, String status, String customer) {
        this.orderId = orderId;
        this.custId = custId;
        this.orderDate = orderDate;
        this.status = status;
        this.customer = customer;
    }

    @Id


    @Column(name="ORDER_ID", unique=true, nullable=false)
    public String getOrderId() {
        return this.orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }


    @Column(name="CUST_ID")
    public String getCustId() {
        return this.custId;
    }

    public void setCustId(String custId) {
        this.custId = custId;
    }


    @Column(name="ORDER_DATE")
    public String getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }


    @Column(name="STATUS")
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


    @Column(name="CUSTOMER")
    public String getCustomer() {
        return this.customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }




}


