package com.solace.connectors.database.sink.entity;
// Generated May 20, 2025, 3:17:44 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;


/**
 * SourceTable generated by hbm2java
 */
@Entity
@Table(name="Logistics::EventHeader1"
    ,schema="TESTSCHEMA"
)
public class SourceTable implements java.io.Serializable {


     private Integer id;
     private String name;
     private BigDecimal amount;
     private String clobcolumn;
     private byte[] blobcolumn;

    public SourceTable() {
    }

	
    public SourceTable(Integer id) {
        this.id = id;
    }
    public SourceTable(Integer id, String name, BigDecimal amount, String clobcolumn, byte[] blobcolumn) {
       this.id = id;
       this.name = name;
       this.amount = amount;
       this.clobcolumn = clobcolumn;
       this.blobcolumn = blobcolumn;
    }
   
     @Id 

    
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="AMOUNT", precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="CLOBCOLUMN")
    public String getClobcolumn() {
        return this.clobcolumn;
    }
    
    public void setClobcolumn(String clobcolumn) {
        this.clobcolumn = clobcolumn;
    }

    
    @Column(name="BLOBCOLUMN")
    public byte[] getBlobcolumn() {
        return this.blobcolumn;
    }
    
    public void setBlobcolumn(byte[] blobcolumn) {
        this.blobcolumn = blobcolumn;
    }




}


