package com.solace.connectors.database.sink.entity;
// Generated May 22, 2025, 12:02:42 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * StatisticsTable generated by hbm2java
 */
@Entity
@Table(name="STATISTICS_TABLE"
    ,schema="TESTSCHEMA"
)
public class StatisticsTable implements java.io.Serializable {


     private Integer sid;
     private String activity;
     private Date transactionTime;
     private String activityId;

    public StatisticsTable() {
    }

	
    public StatisticsTable(Integer sid) {
        this.sid = sid;
    }
    public StatisticsTable(Integer sid, String activity, Date transactionTime, String activityId) {
       this.sid = sid;
       this.activity = activity;
       this.transactionTime = transactionTime;
       this.activityId = activityId;
    }
   
     @Id 

    
    @Column(name="SID", nullable=false)
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    
    @Column(name="ACTIVITY", length=100)
    public String getActivity() {
        return this.activity;
    }
    
    public void setActivity(String activity) {
        this.activity = activity;
    }

    
    @Column(name="TRANSACTION_TIME", length=10)
    public Date getTransactionTime() {
        return this.transactionTime;
    }
    
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }

    
    @Column(name="ACTIVITY_ID", length=100)
    public String getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }




}


