package com.solace.connectors.database.sink.entity;
// Generated Aug 19, 2025, 6:01:10 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TbChild generated by hbm2java
 */
@Entity
@Table(name="TB_CHILD"
    ,schema="C##TEST"
)
public class TbChild implements java.io.Serializable {


     private String parcelid;
     private String traceid;
     private String babylabelid;
     private String scannablebarcode;

    public TbChild() {
    }

	
    public TbChild(String parcelid) {
        this.parcelid = parcelid;
    }
    public TbChild(String parcelid, String traceid, String babylabelid, String scannablebarcode) {
       this.parcelid = parcelid;
       this.traceid = traceid;
       this.babylabelid = babylabelid;
       this.scannablebarcode = scannablebarcode;
    }
   
     @Id 

    
    @Column(name="PARCELID", unique=true, nullable=false)
    public String getParcelid() {
        return this.parcelid;
    }
    
    public void setParcelid(String parcelid) {
        this.parcelid = parcelid;
    }

    
    @Column(name="TRACEID")
    public String getTraceid() {
        return this.traceid;
    }
    
    public void setTraceid(String traceid) {
        this.traceid = traceid;
    }

    
    @Column(name="BABYLABELID")
    public String getBabylabelid() {
        return this.babylabelid;
    }
    
    public void setBabylabelid(String babylabelid) {
        this.babylabelid = babylabelid;
    }

    
    @Column(name="SCANNABLEBARCODE")
    public String getScannablebarcode() {
        return this.scannablebarcode;
    }
    
    public void setScannablebarcode(String scannablebarcode) {
        this.scannablebarcode = scannablebarcode;
    }




}


