package com.solace.connectors.database.sink.entity;
// Generated Aug 19, 2025, 6:01:10 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TbParent generated by hbm2java
 */
@Entity
@Table(name="TB_PARENT"
    ,schema="C##TEST"
)
public class TbParent implements java.io.Serializable {


     private String traceid;
     private String type;
     private String exportdate;
     private String source;
     private String storeid;

    public TbParent() {
    }

	
    public TbParent(String traceid) {
        this.traceid = traceid;
    }
    public TbParent(String traceid, String type, String exportdate, String source, String storeid) {
       this.traceid = traceid;
       this.type = type;
       this.exportdate = exportdate;
       this.source = source;
       this.storeid = storeid;
    }
   
     @Id 

    
    @Column(name="TRACEID", unique=true, nullable=false)
    public String getTraceid() {
        return this.traceid;
    }
    
    public void setTraceid(String traceid) {
        this.traceid = traceid;
    }

    
    @Column(name="TYPE")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="EXPORTDATE")
    public String getExportdate() {
        return this.exportdate;
    }
    
    public void setExportdate(String exportdate) {
        this.exportdate = exportdate;
    }

    
    @Column(name="SOURCE")
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="STOREID")
    public String getStoreid() {
        return this.storeid;
    }
    
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }




}


