package com.solace.connectors.database.source.entity;
// Generated May 19, 2025, 3:05:20 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.util.Date;

/**
 * Ctest generated by hbm2java
 */
@Entity
@Table(name="CTEST"
    ,schema="C##TEST"
)
public class Ctest implements java.io.Serializable {


     private String key;
     private String content;
     private byte[] blobclmn;
     private String flag;
     private Date dbtime;
     private String dbtrackingid;

    public Ctest() {
    }

	
    public Ctest(String key) {
        this.key = key;
    }
    public Ctest(String key, String content, byte[] blobclmn, String flag, Date dbtime, String dbtrackingid) {
       this.key = key;
       this.content = content;
       this.blobclmn = blobclmn;
       this.flag = flag;
       this.dbtime = dbtime;
       this.dbtrackingid = dbtrackingid;
    }
   
     @Id 

    
    @Column(name="KEY", unique=true, nullable=false)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }

    
    @Column(name="CONTENT")
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="BLOBCLMN")
    public byte[] getBlobclmn() {
        return this.blobclmn;
    }
    
    public void setBlobclmn(byte[] blobclmn) {
        this.blobclmn = blobclmn;
    }

    
    @Column(name="FLAG")
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }

    
    @Column(name="DBTIME", length=7)
    public Date getDbtime() {
        return this.dbtime;
    }
    
    public void setDbtime(Date dbtime) {
        this.dbtime = dbtime;
    }

    
    @Column(name="DBTRACKINGID")
    public String getDbtrackingid() {
        return this.dbtrackingid;
    }
    
    public void setDbtrackingid(String dbtrackingid) {
        this.dbtrackingid = dbtrackingid;
    }




}


