package com.solace.connectors.database.source.entity;
// Generated May 20, 2025, 3:17:44 PM by Hibernate Tools 5.6.15.Final



import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * MonitoringSourceTable generated by hbm2java
 */
@Entity
@Table(name="MONITORING_SOURCE_TABLE"
    ,schema="TESTSCHEMA"
)
public class MonitoringSourceTable implements java.io.Serializable {


     private Integer monitoringId;
     private String operationType;
     private Date operationTime;
     private Integer recordId;
     private String oldName;
     private String newName;
     private BigDecimal oldAmount;
     private BigDecimal newAmount;
     private String oldClobcolumn;
     private String newClobcolumn;
     private byte[] oldBlobcolumn;
     private byte[] newBlobcolumn;
     private String dbtrackid;
     private Date readtime;
     private String flag;

    public MonitoringSourceTable() {
    }

	
    public MonitoringSourceTable(Integer monitoringId) {
        this.monitoringId = monitoringId;
    }
    public MonitoringSourceTable(Integer monitoringId, String operationType, Date operationTime, Integer recordId, String oldName, String newName, BigDecimal oldAmount, BigDecimal newAmount, String oldClobcolumn, String newClobcolumn, byte[] oldBlobcolumn, byte[] newBlobcolumn, String dbtrackid, Date readtime, String flag) {
       this.monitoringId = monitoringId;
       this.operationType = operationType;
       this.operationTime = operationTime;
       this.recordId = recordId;
       this.oldName = oldName;
       this.newName = newName;
       this.oldAmount = oldAmount;
       this.newAmount = newAmount;
       this.oldClobcolumn = oldClobcolumn;
       this.newClobcolumn = newClobcolumn;
       this.oldBlobcolumn = oldBlobcolumn;
       this.newBlobcolumn = newBlobcolumn;
       this.dbtrackid = dbtrackid;
       this.readtime = readtime;
       this.flag = flag;
    }
   
     @Id 

    
    @Column(name="MONITORING_ID", nullable=false)
    public Integer getMonitoringId() {
        return this.monitoringId;
    }
    
    public void setMonitoringId(Integer monitoringId) {
        this.monitoringId = monitoringId;
    }

    
    @Column(name="OPERATION_TYPE")
    public String getOperationType() {
        return this.operationType;
    }
    
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    
    @Column(name="OPERATION_TIME", length=27)
    public Date getOperationTime() {
        return this.operationTime;
    }
    
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    
    @Column(name="RECORD_ID")
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    
    @Column(name="OLD_NAME")
    public String getOldName() {
        return this.oldName;
    }
    
    public void setOldName(String oldName) {
        this.oldName = oldName;
    }

    
    @Column(name="NEW_NAME")
    public String getNewName() {
        return this.newName;
    }
    
    public void setNewName(String newName) {
        this.newName = newName;
    }

    
    @Column(name="OLD_AMOUNT", precision=10)
    public BigDecimal getOldAmount() {
        return this.oldAmount;
    }
    
    public void setOldAmount(BigDecimal oldAmount) {
        this.oldAmount = oldAmount;
    }

    
    @Column(name="NEW_AMOUNT", precision=10)
    public BigDecimal getNewAmount() {
        return this.newAmount;
    }
    
    public void setNewAmount(BigDecimal newAmount) {
        this.newAmount = newAmount;
    }

    
    @Column(name="OLD_CLOBCOLUMN")
    public String getOldClobcolumn() {
        return this.oldClobcolumn;
    }
    
    public void setOldClobcolumn(String oldClobcolumn) {
        this.oldClobcolumn = oldClobcolumn;
    }

    
    @Column(name="NEW_CLOBCOLUMN")
    public String getNewClobcolumn() {
        return this.newClobcolumn;
    }
    
    public void setNewClobcolumn(String newClobcolumn) {
        this.newClobcolumn = newClobcolumn;
    }

    
    @Column(name="OLD_BLOBCOLUMN")
    public byte[] getOldBlobcolumn() {
        return this.oldBlobcolumn;
    }
    
    public void setOldBlobcolumn(byte[] oldBlobcolumn) {
        this.oldBlobcolumn = oldBlobcolumn;
    }

    
    @Column(name="NEW_BLOBCOLUMN")
    public byte[] getNewBlobcolumn() {
        return this.newBlobcolumn;
    }
    
    public void setNewBlobcolumn(byte[] newBlobcolumn) {
        this.newBlobcolumn = newBlobcolumn;
    }

    
    @Column(name="DBTRACKID")
    public String getDbtrackid() {
        return this.dbtrackid;
    }
    
    public void setDbtrackid(String dbtrackid) {
        this.dbtrackid = dbtrackid;
    }

    
    @Column(name="READTIME", length=27)
    public Date getReadtime() {
        return this.readtime;
    }
    
    public void setReadtime(Date readtime) {
        this.readtime = readtime;
    }

    
    @Column(name="FLAG")
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }




}


